# Site settings
title: Blog
email: josh@goatslacker.com
description: > # this means to ignore newlines until "baseurl:"
  Things about Software
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://words.goatslacker.com" # the base hostname & protocol for your site
twitter_username: goatslacker
github_username:  goatslacker

# Build settings
markdown: kramdown
